## defaults for _all_ profiles
[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.15" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
eth-rpc-url = "http://localhost:8545"
